name: Extract Changelog entries for most recent version
description: Extracts entries from the changelog file for the most recent version and writes them to a file.
inputs:
  changelog-file:
    description: 'Path to the changelog file, relative to the workspace.'
    required: false
    default: 'CHANGELOG.md'
  output-file:
    description: 'The file to write the extracted entries to, relative to the workspace.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: [
    "changelog", "extract",
    "--quiet",
    "--changelog", "/github/workspace/${{ inputs.changelog-file }}",
    "--output-file", "/github/workspace/${{ inputs.output-file }}"
  ]
