name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.3'

      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build

      - name: Dryrun changelog
        run: |
          ./since > /tmp/changes.md
          cat /tmp/changes.md
